FROM node 
WORKDIR C:\Users\PC\OneDrive\Documents\DEVOPS\Docker\docker-react\srcC:\Users\PC\OneDrive\Documents\DEVOPS\Docker\docker-react\src
COPY package.json .
RUN npm install
COPY . . 
EXPOSE 3000
CMD ["npm", "start"] 

